Repository sihyun615/refrigerator, pull requests merged in 2024-07, with the labels that each got.

#14 feat/user >> user 전체 기능
  src/main/java/com/sparta/refrigerator/auth/config/SecurityConfig.java
  src/main/java/com/sparta/refrigerator/auth/config/WebSecurityConfig.java
  src/main/java/com/sparta/refrigerator/auth/controller/UserController.java
  src/main/java/com/sparta/refrigerator/auth/controller/c.java
  src/main/java/com/sparta/refrigerator/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/refrigerator/auth/dto/PasswordRequestDto.java
  src/main/java/com/sparta/refrigerator/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/refrigerator/auth/dto/c.java
  src/main/java/com/sparta/refrigerator/auth/entity/User.java
  src/main/java/com/sparta/refrigerator/auth/entity/c.java
  src/main/java/com/sparta/refrigerator/auth/enumeration/TokenError.java
  src/main/java/com/sparta/refrigerator/auth/enumeration/UserAuth.java
  src/main/java/com/sparta/refrigerator/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/refrigerator/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/refrigerator/auth/jwt/JwtUtil.java
  src/main/java/com/sparta/refrigerator/auth/repository/UserRepository.java
  src/main/java/com/sparta/refrigerator/auth/repository/c.java
  src/main/java/com/sparta/refrigerator/auth/service/UserDetailsImpl.java
  src/main/java/com/sparta/refrigerator/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/sparta/refrigerator/auth/service/UserService.java
  src/main/java/com/sparta/refrigerator/exception/ErrorCode.java
  src/main/java/com/sparta/refrigerator/exception/UserException.java
Labels: 🌟 feat

#11 feat/board >> board 기능 생성
  src/main/java/com/sparta/refrigerator/board/controller/BoardController.java
  src/main/java/com/sparta/refrigerator/board/dto/BoardRequestDTO.java
  src/main/java/com/sparta/refrigerator/board/dto/BoardResponseDTO.java
  src/main/java/com/sparta/refrigerator/board/dto/InvitationRequestDTO.java
  src/main/java/com/sparta/refrigerator/board/dto/f.java
  src/main/java/com/sparta/refrigerator/board/entity/Board.java
  src/main/java/com/sparta/refrigerator/board/entity/Invitation.java
  src/main/java/com/sparta/refrigerator/board/repository/BoardRepository.java
  src/main/java/com/sparta/refrigerator/board/repository/InvitationRepository.java
  src/main/java/com/sparta/refrigerator/board/repository/c.java
  src/main/java/com/sparta/refrigerator/board/repository/hi.java
  src/main/java/com/sparta/refrigerator/board/service/BoardService.java
  src/main/java/com/sparta/refrigerator/board/service/c.java
  src/main/java/com/sparta/refrigerator/board/service/hi.java
Labels: 🌟 feat

#12 feat/column >> 컬럼 전체 기능
  src/main/java/com/sparta/refrigerator/auth/entity/User.java
  src/main/java/com/sparta/refrigerator/column/controller/ColumnController.java
  src/main/java/com/sparta/refrigerator/column/controller/hi.java
  src/main/java/com/sparta/refrigerator/column/dto/ColumnMoveRequestDto.java
  src/main/java/com/sparta/refrigerator/column/dto/ColumnRequestDto.java
  src/main/java/com/sparta/refrigerator/column/dto/ColumnResponseDto.java
  src/main/java/com/sparta/refrigerator/column/dto/hi.java
  src/main/java/com/sparta/refrigerator/column/entity/Column.java
  src/main/java/com/sparta/refrigerator/column/entity/hi.java
  src/main/java/com/sparta/refrigerator/column/repository/ColumnRepository.java
  src/main/java/com/sparta/refrigerator/column/repository/q.java
  src/main/java/com/sparta/refrigerator/column/service/ColumnService.java
  src/main/java/com/sparta/refrigerator/column/service/q.java
Labels: 🌟 feat

#13 feat/card>> 카드 CRUD 기능
  src/main/java/com/sparta/refrigerator/board/entity/Board.java
  src/main/java/com/sparta/refrigerator/card/controller/CardController.java
  src/main/java/com/sparta/refrigerator/card/controller/hi.java
  src/main/java/com/sparta/refrigerator/card/dto/CardRequestDto.java
  src/main/java/com/sparta/refrigerator/card/dto/CardResponseDto.java
  src/main/java/com/sparta/refrigerator/card/dto/hi.java
  src/main/java/com/sparta/refrigerator/card/entity/Card.java
  src/main/java/com/sparta/refrigerator/card/entity/hi.java
  src/main/java/com/sparta/refrigerator/card/repository/CardRepository.java
  src/main/java/com/sparta/refrigerator/card/repository/hi.java
  src/main/java/com/sparta/refrigerator/card/service/CardService.java
  src/main/java/com/sparta/refrigerator/card/service/hi.java
  src/main/java/com/sparta/refrigerator/exception/CardNotFoundException.java
Labels: 🌟 feat

#18 [Bug] Board 오류 테스트
  src/main/java/com/sparta/refrigerator/board/controller/BoardController.java
  src/main/java/com/sparta/refrigerator/board/dto/BoardResponseDTO.java
  src/main/java/com/sparta/refrigerator/board/entity/Board.java
  src/main/java/com/sparta/refrigerator/board/entity/Invitation.java
  src/main/java/com/sparta/refrigerator/board/repository/InvitationRepository.java
  src/main/java/com/sparta/refrigerator/board/service/BoardService.java
Labels: 👾 bug

#20 feat/user >> 토큰 발급 및 재발급 부분 수정
  src/main/java/com/sparta/refrigerator/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/refrigerator/auth/jwt/JwtUtil.java
  src/main/java/com/sparta/refrigerator/auth/service/UserService.java
Labels: ♻️ refactor

#19 [Feat] Board 초대 코드 추가 및 수정
  src/main/java/com/sparta/refrigerator/board/controller/BoardController.java
  src/main/java/com/sparta/refrigerator/board/entity/Invitation.java
  src/main/java/com/sparta/refrigerator/board/repository/InvitationRepository.java
  src/main/java/com/sparta/refrigerator/board/service/BoardService.java
Labels: 🌟 feat

#27 [Feat] Board 양방향 관계 설정 코드 수정
  src/main/java/com/sparta/refrigerator/board/entity/Board.java
Labels: ♻️ refactor

#26 feat/user >> User Frontend 연동 추가
  src/main/java/com/sparta/refrigerator/auth/controller/UserController.java
  src/main/java/com/sparta/refrigerator/auth/dto/SignupRequestDto.java
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: 🌟 feat

#29 ✨ update : 카드 상세기능추가
  src/main/java/com/sparta/refrigerator/card/controller/CardController.java
  src/main/java/com/sparta/refrigerator/card/dto/CardRequestDto.java
  src/main/java/com/sparta/refrigerator/card/dto/CardResponseDto.java
  src/main/java/com/sparta/refrigerator/card/entity/Card.java
  src/main/java/com/sparta/refrigerator/card/repository/CardRepository.java
  src/main/java/com/sparta/refrigerator/card/service/CardService.java
  src/main/java/com/sparta/refrigerator/column/entity/Columns.java
  src/main/java/com/sparta/refrigerator/exception/UserMisMatchException.java
Labels: 🌟 feat

#30 ✨ update : #15 카드 연관관계 추가
  src/main/java/com/sparta/refrigerator/card/entity/Card.java
Labels: 🌟 feat

#9 feat/comment >> 댓글 기능 추가
  src/main/java/com/sparta/refrigerator/comment/controller/CommentController.java
  src/main/java/com/sparta/refrigerator/comment/controller/hi.java
  src/main/java/com/sparta/refrigerator/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/refrigerator/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/refrigerator/comment/dto/c.java
  src/main/java/com/sparta/refrigerator/comment/dto/hi.java
  src/main/java/com/sparta/refrigerator/comment/entity/Comment.java
  src/main/java/com/sparta/refrigerator/comment/entity/c.java
  src/main/java/com/sparta/refrigerator/comment/repository/CommentRepository.java
  src/main/java/com/sparta/refrigerator/comment/repository/c.java
  src/main/java/com/sparta/refrigerator/comment/service/CommentService.java
  src/main/java/com/sparta/refrigerator/comment/service/c.java
Labels: 🌟 feat

#33 feat/comment >> Comment 관련 코드 수정
  src/main/java/com/sparta/refrigerator/comment/controller/CommentController.java
  src/main/java/com/sparta/refrigerator/comment/repository/CommentRepository.java
  src/main/java/com/sparta/refrigerator/comment/service/CommentService.java
Labels: 👾 bug, 🌟 feat

#47 ✨ update : #? 카드이동기능 추가
  src/main/java/com/sparta/refrigerator/card/controller/CardController.java
  src/main/java/com/sparta/refrigerator/card/dto/CardMoveRequestDto.java
  src/main/java/com/sparta/refrigerator/card/entity/Card.java
  src/main/java/com/sparta/refrigerator/card/repository/CardRepository.java
  src/main/java/com/sparta/refrigerator/card/service/CardService.java
Labels: 🌟 feat

#48 ✨ update : #? 칼럼 이동 백엔드연결구현
  src/main/java/com/sparta/refrigerator/column/service/ColumnService.java
  src/main/resources/templates/scripts2.js
Labels: 🌟 feat

#54 🎉 add : #53 카드 수정 API 연결
  src/main/resources/templates/index.html
  src/main/resources/templates/scripts2.js
Labels: 🌟 feat
